/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
package com.dell.isg.smi.commons.elm.model;

import com.dell.isg.smi.commons.elm.messaging.IMessageEnum;

public enum EnumErrorCode implements IMessageEnum {
    /*
     * ENUM_PROFILE_TYPE_INVALID("ENUM_PROFILE_TYPE_INVALID",220001), ENUM_CREDENTIAL_TYPE_INVALID("ENUM_CREDENTIAL_TYPE_INVALID",220002),
     * ENUM_CREDENTIAL_INVALID("ENUM_CREDENTIAL_INVALID",220003), ENUM_CREDENTIAL_SAVE_ERROR("ENUM_CREDENTIAL_SAVE_ERROR",220004),
     * ENUM_CONNECTION_CREDENTIAL_SAVE_ERROR("ENUM_CONNECTION_CREDENTIAL_SAVE_ERROR",220005),
     * ENUM_NO_CONNECTION_PROFILE_PROFILE_ERROR("ENUM_NO_CONNECTION_PROFILE_PROFILE_ERROR",220006),
     * ENUM_CONNECTION_PROFILE_FETCH_ERROR("ENUM_CONNECTION_PROFILE_FETCH_ERROR",220007), CHASSIS_IP_INVALID("CHASSIS_IP_INVALID",260001),
     * CHASSIS_SERVICETAG_INVALID("CHASSIS_SERVICETAG_INVALID",260002), CHASSIS_ADAPTER_COMMAND_FAILED("CHASSIS_ADAPTER_COMMAND_FAILED",260003),
     * SERVER_ADAPTER_COMMAND_FAILED("SERVER_ADAPTER_COMMAND_FAILED",270001), SWITCH_PORT_SUMMARY_FAILED("SWITCH_PORT_SUMMARY_FAILED",250001),
     * FABRIC_DETAILS_FAILED("FABRIC_DETAILS_FAILED",250002), SWITCH_DETAILS_FAILED("SWITCH_DETAILS_FAILED",250003),
     * CONFIGURE_FABRIC_UPLINKS_FAILED("CONFIGURE_FABRIC_UPLINKS_FAILED",250004), UPDATE_FABRIC_UPLINKS_FAILED("UPDATE_FABRIC_UPLINKS_FAILED",250005),
     * DELETE_FABRIC_UPLINKS_FAILED("DELETE_FABRIC_UPLINKS_FAILED",250006), ENUM_UNKNOWN_ERROR("ENUM_UNKNOWN_ERROR",200001),
     * ENUM_AUTHORIZATION_ERROR("ENUM_AUTHORIZATION_ERROR",200003), ENUM_AUTHENTICATION_ERROR("ENUM_AUTHENTICATION_ERROR",200004),
     * ENUM_INVALIDINPUT_ERROR("ENUM_INVALIDINPUT_ERROR",200005), ENUM_UNSUPPORTEDOPERATION_ERROR("ENUM_UNSUPPORTEDOPERATION_ERROR",200006),
     * ENUM_INTERNAL_ERROR("ENUM_INTERNAL_ERROR",200007), ENUM_COMMUNICATION_ERROR("ENUM_COMMUNICATION_ERROR",200008), ENUM_LOCKED_ERROR("ENUM_LOCKED_ERROR",200009),
     * ENUM_UNKNOWN_ACCOUNT_ERROR("ENUM_UNKNOWN_ACCOUNT_ERROR",200010), ENUM_INCORRECT_CREDENTIALS_ERROR("ENUM_INCORRECT_CREDENTIALS_ERROR",200011),
     * ENUM_EXCESSIVE_ATTEMPTS_ERROR("ENUM_EXCESSIVE_ATTEMPTS_ERROR",200012), ENUM_INVALID_DATA_WITHOUT_PARAM_NAME("ENUM_INVALID_DATA_WITHOUT_PARAM_NAME",200013),
     * ENUM_LICENSE_EXPIRED("ENUM_LICENSE_EXPIRED",200014), ENUM_LICENSE_NOT_VALID("ENUM_LICENSE_NOT_VALID",200015),
     * ENUM_BAD_REQUEST_ERROR("ENUM_BAD_REQUEST_ERROR",200400), ENUM_NOT_FOUND_ERROR("ENUM_NOT_FOUND_ERROR",200404), ENUM_CONFLICT("ENUM_CONFLICT",200409),
     * ENUM_NOT_FOUND_DEVICE_STATE_ERROR("ENUM_NOT_FOUND_DEVICE_STATE_ERROR",201404), ENUM_NOT_FOUND_DEVICE_STATUS_ERROR("ENUM_NOT_FOUND_DEVICE_STATUS_ERROR",201409),
     * ENUM_TOO_MANY_REQUESTS("ENUM_TOO_MANY_REQUESTS",200429), ENUM_SERVER_ERROR("ENUM_SERVER_ERROR",200500), INVALID_NEGATIVE_INPUT("INVALID_NEGATIVE_INPUT",200501),
     * ENUM_PERMISSION_ERROR("ENUM_PERMISSION_ERROR",200502), NO_RECORD_FOUND("NO_RECORD_FOUND",230001), IOPOOL_DELETE_NOT_ALLOWED("IOPOOL_DELETE_NOT_ALLOWED",230002),
     * CANNOT_RETRIEVE_DATA("CANNOT_RETRIEVE_DATA",231011), IOIDENTITY_INVALID_TYPE_IN_POOL("IOIDENTITY_INVALID_TYPE_IN_POOL",231012),
     * IPPOOL_INVALID_IPADRESS_COUNT("IPPOOL_INVALID_IPADRESS_COUNT",233002), IPPOOL_INVALID_IPADRESS_LIST("IPPOOL_INVALID_IPADRESS_LIST",233003),
     * INVALID_NAME_LENGTH_CODE("INVALID_NAME_LENGTH_CODE",234001), INVALID_NAME_FORMAT_CODE("INVALID_NAME_FORMAT_CODE",234002),
     * INVALID_DESC_LENGTH_CODE("INVALID_DESC_LENGTH_CODE",234003), INVALID_DESC_FORMAT_CODE("INVALID_DESC_FORMAT_CODE",234004),
     * INVALID_DISPLAY_NAME_LENGTH_CODE("INVALID_DISPLAY_NAME_LENGTH_CODE",234015), INVALID_DISPLAY_NAME_FORMAT_CODE("INVALID_DISPLAY_NAME_FORMAT_CODE",234016),
     * INVALID_IPADDRESS_CODE("INVALID_IPADDRESS_CODE",234022), INVALID_IPRANGE_CODE("INVALID_IPRANGE_CODE",234024), INVALID_IPRANGE_SIZE_CODE("INVALID_IPRANGE_SIZE_CODE",234025),
     * USERNAME_MISSING("USERNAME_MISSING",700001), USERNAME_INVALID("USERNAME_INVALID",700002), PASSWORD_MISSING("PASSWORD_MISSING",700003),
     * PASSWORD_INVALID("PASSWORD_INVALID",700004), USERNAME_NOT_UNIQUE("USERNAME_NOT_UNIQUE",700005), INVALID_USERTYPE("INVALID_USERTYPE",700006),
     * ENUM_APPLIANCE_PASSWORD_INVALID("ENUM_APPLIANCE_PASSWORD_INVALID",210001),
     * ENUM_APPLIANCE_PASSWORD_CHANGE_UNKNOWN_ERROR("ENUM_APPLIANCE_PASSWORD_CHANGE_UNKNOWN_ERROR",210002),
     * ENUM_APPLIANCE_PASSWORD_UNSECURE("ENUM_APPLIANCE_PASSWORD_UNSECURE",210003), ENUM_APPLIANCE_HOSTNAME_GET_UNKNOWN_ERROR("ENUM_APPLIANCE_HOSTNAME_GET_UNKNOWN_ERROR",210010),
     * ENUM_APPLIANCE_HOSTNAME_CHANGE_UNKNOWN_ERROR("ENUM_APPLIANCE_HOSTNAME_CHANGE_UNKNOWN_ERROR",210011),
     * ENUM_APPLIANCE_CERTIFICATE_SIGNING_REQUEST_UNKNOWN_ERROR("ENUM_APPLIANCE_CERTIFICATE_SIGNING_REQUEST_UNKNOWN_ERROR",210020),
     * ENUM_APPLIANCE_TIMEZONE_GET_UNKNOWN_ERROR("ENUM_APPLIANCE_TIMEZONE_GET_UNKNOWN_ERROR",210030),
     * ENUM_APPLIANCE_TIMEZONES_GET_UNKNOWN_ERROR("ENUM_APPLIANCE_TIMEZONES_GET_UNKNOWN_ERROR",210031),
     * ENUM_APPLIANCE_TIMEZONE_CHANGE_UNKNOWN_ERROR("ENUM_APPLIANCE_TIMEZONE_CHANGE_UNKNOWN_ERROR",210032),
     * ENUM_NTP_SETTINGS_CONFIGURATION_PERSIST_ERROR("ENUM_NTP_SETTINGS_CONFIGURATION_PERSIST_ERROR",210033),
     * ENUM_APPLIANCE_SHUTDOWN_UNKNOWN_ERROR("ENUM_APPLIANCE_SHUTDOWN_UNKNOWN_ERROR",210040), ENUM_APPLIANCE_RESTART_UNKNOWN_ERROR("ENUM_APPLIANCE_RESTART_UNKNOWN_ERROR",210041),
     * ENUM_APPLIANCE_TROUBLESHOOTING_BUNDLE_ERROR("ENUM_APPLIANCE_TROUBLESHOOTING_BUNDLE_ERROR",210042),
     * ENUM_TENANT_ENTITY_ASSOCIATION_CREATION_FAILURE("ENUM_TENANT_ENTITY_ASSOCIATION_CREATION_FAILURE",210050),
     * ENUM_SYSLOGSETTINGS_CONFIGURATION_PERSIST_ERROR("ENUM_SYSLOGSETTINGS_CONFIGURATION_PERSIST_ERROR",210060),
     * ENUM_SNMPSETTINGS_NETWORK_SERVICE_PERSIST_ERROR("ENUM_SNMPSETTINGS_NETWORK_SERVICE_PERSIST_ERROR",210070),
     * ENUM_PROXYINFORMATION_CONFIGURATION_PERSIST_ERROR("ENUM_PROXYINFORMATION_CONFIGURATION_PERSIST_ERROR",210080),
     * ENUM_PROXYINFORMATION_TEST_ERROR_NO_HOST_DETAIL("ENUM_PROXYINFORMATION_TEST_ERROR_NO_HOST_DETAIL",210082), ENUM_GET_AUDIT_DATA_FAILURE("ENUM_GET_AUDIT_DATA_FAILURE",210090),
     * ENUM_SMTPSETTINGS_CONFIGURATION_PERSIST_ERROR("ENUM_SMTPSETTINGS_CONFIGURATION_PERSIST_ERROR",210100), ENUM_SMTPSETTINGS_TEST_ERROR("ENUM_SMTPSETTINGS_TEST_ERROR",210101),
     * ENUM_DATABASE_OBJECT_NOT_FOUND("ENUM_DATABASE_OBJECT_NOT_FOUND",210200),
     * STORAGE_CONTROLLER_PASSWORD_CHANGE_UNKNOWN_ERROR("STORAGE_CONTROLLER_PASSWORD_CHANGE_UNKNOWN_ERROR",240001), STORAGE_HOST_NOT_AVAILABLE("STORAGE_HOST_NOT_AVAILABLE",240002),
     * STORAGE_GET_CURRENT_USER_FAILED("STORAGE_GET_CURRENT_USER_FAILED",240003), STORAGE_NO_DISK_FOUND_ERROR("STORAGE_NO_DISK_FOUND_ERROR",240004),
     * STORAGE_CREATE_DISK_FAILED("STORAGE_CREATE_DISK_FAILED",240005), STORAGE_JOIN_CONTROLLER_FAILED("STORAGE_JOIN_CONTROLLER_FAILED",240006),
     * INVALID_STORAGEID_VOLUMEID_ASSOCIATION("INVALID_STORAGEID_VOLUMEID_ASSOCIATION",240007), STORAGE_NOT_FOUND("STORAGE_NOT_FOUND",240008),
     * STORAGE_GET_EM_USER_ERROR("STORAGE_GET_EM_USER_ERROR",240009), STORAGE_CHANGE_USER_CREDENTIAL_ERROR("STORAGE_CHANGE_USER_CREDENTIAL_ERROR",240010),
     * STORAGE_EULA_ACCEPTANCE_ERROR("STORAGE_EULA_ACCEPTANCE_ERROR",240011), STORAGE_CONFIGURE_TIMEZONE_ERROR("STORAGE_CONFIGURE_TIMEZONE_ERROR",240012),
     * STORAGE_NO_DISK_FOLDER_FOUND_ERROR("STORAGE_NO_DISK_FOLDER_FOUND_ERROR",240013), STORAGE_MANAGE_REMAINING_DISK_ERROR("STORAGE_MANAGE_REMAINING_DISK_ERROR",240014),
     * STORAGE_CONFIGURE_SNMP_TRAP_ERROR("STORAGE_CONFIGURE_SNMP_TRAP_ERROR",240015), STORAGE_GENERATE_SSL_CERTIFICATE_ERROR("STORAGE_GENERATE_SSL_CERTIFICATE_ERROR",240016),
     * STORAGE_CREATE_BACK_END_LOCAL_PORT_CONFIGURATION_ERROR("STORAGE_CREATE_BACK_END_LOCAL_PORT_CONFIGURATION_ERROR",240017),
     * STORAGE_CONFIGURE_CACHE_ERROR("STORAGE_CONFIGURE_CACHE_ERROR",240018), STORAGE_CONFIGURE_LOGGING_AND_UPDATE_ERROR("STORAGE_CONFIGURE_LOGGING_AND_UPDATE_ERROR",240019),
     * STORAGE_VOLUME_CREATE_ERROR("STORAGE_VOLUME_CREATE_ERROR",240020), STORAGE_VOLUME_GET_LIST_ERROR("STORAGE_VOLUME_GET_LIST_ERROR",240021),
     * STORAGE_VOLUME_GET_ERROR("STORAGE_VOLUME_GET_ERROR",240022), STORAGE_VOLUME_UPDATE_NAME_ERROR("STORAGE_VOLUME_UPDATE_NAME_ERROR",240023),
     * STORAGE_VOLUME_UPDATE_STORAGE_PROFILE_ERROR("STORAGE_VOLUME_UPDATE_STORAGE_PROFILE_ERROR",240024),
     * STORAGE_VOLUME_UPDATE_SIZE_ERROR("STORAGE_VOLUME_UPDATE_SIZE_ERROR",240025), STORAGE_VOLUME_DELETE_ERROR("STORAGE_VOLUME_DELETE_ERROR",240026),
     * STORAGE_VOLUME_NOT_FOUND("STORAGE_VOLUME_NOT_FOUND",240027), STORAGE_SNAPSHOT_CREATE_ERROR("STORAGE_SNAPSHOT_CREATE_ERROR",240028),
     * STORAGE_SNAPSHOT_GET_LIST_ERROR("STORAGE_SNAPSHOT_GET_LIST_ERROR",240029), STORAGE_SNAPSHOT_GET_ERROR("STORAGE_SNAPSHOT_GET_ERROR",240030),
     * STORAGE_SNAPSHOT_UPDATE_ERROR("STORAGE_SNAPSHOT_UPDATE_ERROR",240031), STORAGE_SNAPSHOT_DELETE_ERROR("STORAGE_SNAPSHOT_DELETE_ERROR",240032),
     * INVALID_VOLUMEID_SNAPSHOTID_ASSOCIATION("INVALID_VOLUMEID_SNAPSHOTID_ASSOCIATION",240033),
     * STORAGE_SNAPSHOT_CREATE_INACTIVE_ERROR("STORAGE_SNAPSHOT_CREATE_INACTIVE_ERROR",240034),
     * STORAGE_VOLUME_CREATE_FROM_SNAPSHOT_ERROR("STORAGE_VOLUME_CREATE_FROM_SNAPSHOT_ERROR",240035),
     * STORAGE_SNAPSHOT_SCHEDULE_CREATE_ERROR("STORAGE_SNAPSHOT_SCHEDULE_CREATE_ERROR",240036),
     * STORAGE_SNAPSHOT_SCHEDULE_UPDATE_ERROR("STORAGE_SNAPSHOT_SCHEDULE_UPDATE_ERROR",240037), STORAGE_SNAPSHOT_SCHEDULE_GET_ERROR("STORAGE_SNAPSHOT_SCHEDULE_GET_ERROR",240038),
     * STORAGE_SNAPSHOT_SCHEDULE_DELETE_ERROR("STORAGE_SNAPSHOT_SCHEDULE_DELETE_ERROR",240039), INVALID_SNAPSHOT_SCHEDULE_START_TIME("INVALID_SNAPSHOT_SCHEDULE_START_TIME",240040),
     * MISSING_MANDATORY_INPUT_FIELD("MISSING_MANDATORY_INPUT_FIELD",240041), INVALID_TYPE_ERROR("INVALID_TYPE_ERROR",240041),
     * INVALID_SNAPSHOT_SCHEDULE("INVALID_SNAPSHOT_SCHEDULE",240042), STORAGE_IO_PORTS_CONFIGURATION("STORAGE_IO_PORTS_CONFIGURATION",240043),
     * STORAGE_IO_PORTS_NOT_ENOUGH("STORAGE_IO_PORTS_NOT_ENOUGH",240044), STORAGE_CHECK_IO_PORTS_CONFIGURED("STORAGE_CHECK_IO_PORTS_CONFIGURED",240045),
     * STORAGE_REBALANCING_IO_PORTS("STORAGE_REBALANCING_IO_PORTS",240046), STORAGE_ONBOARDING_IP_NOT_ENOUGH("STORAGE_ONBOARDING_IP_NOT_ENOUGH",240047),
     * SNAPSHOT_SCHEDULE_HAS_VOLUMES("SNAPSHOT_SCHEDULE_HAS_VOLUMES",240048), STORAGE_REBOOT_ERROR("STORAGE_REBOOT_ERROR",240049),
     * STORAGE_POWEROFF_ERROR("STORAGE_POWEROFF_ERROR",240050),
     */
    ENUM_INPUT_EXCEEDED_MAXIMUM_LENGTH("ENUM_INPUT_EXCEEDED_MAXIMUM_LENGTH",200016),
    ENUM_INPUT_EXCEEDED_TOTAL("ENUM_INPUT_EXCEEDED_TOTAL",200017),
    ENUM_INVALID_DATA("ENUM_INVALID_DATA", 200002),
    ENUM_COMMUNICATION_ERROR("ENUM_COMMUNICATION_ERROR", 200008),
    ENUM_GENERIC_MESSAGE("ENUM_GENERIC_MESSAGE", 201410),
	ENUM_INACCESSIBLE_IP("ENUM_INACCESSIBLE_IP", 234023);
	
    private Integer id;
    private String value;


    private EnumErrorCode(String value, Integer id) {
        this.value = value;
        this.id = id;
    }


    public String getValue() {
        return this.value;
    }


    public Integer getId() {
        return this.id;
    }


    public String toString() {
        return this.value;
    }
}
