/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.04 at 01:18:28 PM CST
//

package com.dell.isg.smi.commons.elm.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LocalizedMessage complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LocalizedMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageEntityList" type="{http://esg.dell.com/icee/common/model}MessageEntity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MessageGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalizedMessage", propOrder = { "messageEntityList", "messageGroup" })
public class LocalizedMessage {

    @XmlElement(name = "MessageEntityList")
    protected List<MessageEntity> messageEntityList;
    @XmlElement(name = "MessageGroup")
    protected String messageGroup;


    /**
     * Gets the value of the messageEntityList property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageEntityList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getMessageEntityList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link MessageEntity }
     *
     *
     */
    public List<MessageEntity> getMessageEntityList() {
        if (messageEntityList == null) {
            messageEntityList = new ArrayList<MessageEntity>();
        }
        return this.messageEntityList;
    }


    /**
     * Gets the value of the messageGroup property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessageGroup() {
        return messageGroup;
    }


    /**
     * Sets the value of the messageGroup property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMessageGroup(String value) {
        this.messageGroup = value;
    }

}
