/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.04 at 01:18:28 PM CST
//

package com.dell.isg.smi.commons.elm.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * The Class MessageEntity.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageEntity", propOrder = { "messageCode", "messageParams", "creationTime", "messagePriority", "groupOrder", "messageGroup" })
public class MessageEntity {

    @XmlElement(name = "MessageCode")
    protected String messageCode;
    @XmlElement(name = "MessageParams")
    protected String messageParams;
    @XmlElement(name = "CreationTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    @XmlElement(name = "MessagePriority")
    protected String messagePriority;
    @XmlElement(name = "GroupOrder")
    protected String groupOrder;
    @XmlElement(name = "MessageGroup")
    protected String messageGroup;


    /**
     * Gets the value of the messageCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessageCode() {
        return messageCode;
    }


    /**
     * Sets the value of the messageCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMessageCode(String value) {
        this.messageCode = value;
    }


    /**
     * Gets the value of the messageParams property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessageParams() {
        return messageParams;
    }


    /**
     * Sets the value of the messageParams property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMessageParams(String value) {
        this.messageParams = value;
    }


    /**
     * Gets the value of the creationTime property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }


    /**
     * Sets the value of the creationTime property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }


    /**
     * Gets the value of the messagePriority property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessagePriority() {
        return messagePriority;
    }


    /**
     * Sets the value of the messagePriority property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMessagePriority(String value) {
        this.messagePriority = value;
    }


    /**
     * Gets the value of the groupOrder property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGroupOrder() {
        return groupOrder;
    }


    /**
     * Sets the value of the groupOrder property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGroupOrder(String value) {
        this.groupOrder = value;
    }


    /**
     * Gets the value of the messageGroup property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessageGroup() {
        return messageGroup;
    }


    /**
     * Sets the value of the messageGroup property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMessageGroup(String value) {
        this.messageGroup = value;
    }

}
