/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.04 at 01:18:28 PM CST
//

package com.dell.isg.smi.commons.elm.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Pagination complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Pagination">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pagination", propOrder = { "offset", "limit", "total" })
public class Pagination {

    protected long offset;
    protected long limit;
    protected long total;


    /**
     * Gets the value of the offset property.
     *
     */
    public long getOffset() {
        return offset;
    }


    /**
     * Sets the value of the offset property.
     *
     */
    public void setOffset(long value) {
        this.offset = value;
    }


    /**
     * Gets the value of the limit property.
     *
     */
    public long getLimit() {
        return limit;
    }


    /**
     * Sets the value of the limit property.
     *
     */
    public void setLimit(long value) {
        this.limit = value;
    }


    /**
     * Gets the value of the total property.
     *
     */
    public long getTotal() {
        return total;
    }


    /**
     * Sets the value of the total property.
     *
     */
    public void setTotal(long value) {
        this.total = value;
    }

}
